[build]
  command = "npm run build"
  publish = "dist/weather-app"

[context.production.environment]
  NODE_VERSION = "14.20.0"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
