[build]
  command = "npm run build"
  publish = "dist/todo"

[context.production.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
